# permissions for end users to view visitorapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: visitorapp-viewer-role
rules:
- apiGroups:
  - javiroman.javiroman.lan
  resources:
  - visitorapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - javiroman.javiroman.lan
  resources:
  - visitorapps/status
  verbs:
  - get
