package io.fabric8;

import io.fabric8.kubernetes.client.Config;
import io.fabric8.kubernetes.client.ConfigBuilder;

public class EnvironmentKubernetesConfig {

    public Config loadConfig() {
    Config properties = new ConfigBuilder()
            .withMasterUrl("https://k8s-master.kubernetes.lan:6443")
            .withApiVersion("v1")
            .withClientKeyAlgo("RSA")
            .withUsername("kubernetes-admin-vagrant")
            .withClientCertData("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJTVhacU9FOWNqT013RFFZ" +
                    "SktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TWpBek1qSXdPREF3TlRaYUZ3" +
                    "MHlNekF6TWpJd09EQXdOVGhhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJk" +
                    "V0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXQ5WFF4VVBi" +
                    "dmdxYUlDS28KY2htVVVRbzUva1N6T1dKK1ZZSDUvVzF4MTNFcHZsaWFqenJGbDdpQWJYaWUyTFBjRHNXemI0aG5EV0hqdlVo" +
                    "YgpjbnpCQkN6LzFPRnpQMWRyYjhIbWdDb09ENEcyWXhPTUdSeGNJOWhjeXMrdU9VRkNXbU5vQnZWZ0Z1WVRlQ2kvCnZVVEhR" +
                    "bFYxbnNBdjE3bkxzZW5uZ2Rkc2xiQXpQL2cyNGtnNG9kaUVENmtPSW42SHlNYWdheWp6WWZueE1SOGUKdGJqb2dOR1I5dlV1" +
                    "Uk1BZDgyMFJUUDRMeEh5VmZNZlFjak0xa2h4d3Nmd2llcENjZFdsVjkvdzFhNmtrVVFuQgpCeGgxcUlTbWZwSTcra3QycUlp" +
                    "c3BFNzBnU0Y1NUFXQ2NlUyt4USs1ekczaEJ1V3BtVDA0aU45S2VoZDBZLy9XCkhvM0VmUUlEQVFBQm8xWXdWREFPQmdOVkhR" +
                    "OEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVH" +
                    "REFXZ0JSSDZTY0s4K0ZReVVHSjB1Sm9UZ2xsWFB6Uwo4ekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBaSt0V3B4b3hIR1gr" +
                    "NTBIUm1XSnpsYlhoc2NhdVJ2VDJEdVdzCkNsOFdKYmh5VmhkQmQvVEd1UUE5MThzd2VsNEY2Q3QzZ0hUQWMvMDJxL1phdytX" +
                    "WThCOCtHeUx5TjlTWjJsRmgKWmRyWnNOVVJEM2VaR2RYRGVmOExBaldSbVZaOGsvaHM2UU1sYTJQUUppa0hTbUsvOFNrL09C" +
                    "dVpEWHAzYTJMMAp1UHBmdGFKdHVBcGJ0eDB5MXpNSHE2aEovdUhDNTl2UnRJNzV0dFhKeWoweGg0L2xvWXlQbFBxM3RpYWdx" +
                    "c1BYCmNsbmNnTXFrc0tCaFluTWRtR3pTWE9oTkM0U3pUUWNrT0tmekE3TWtqVCtNQWRrQzdQc0thSlRjT3hnTXF3WDEKb0N2" +
                    "RHlUa2NyM3gxRWVwYVBwOWdHc2RybVRMNUZWMGJGQzlCZnNVd1I1WmErZU1EMlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0t" +
                    "LS0tCg==")
            .withClientKeyData("LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdDlYUXhVUGJ2Z3FhSUNLb" +
                    "2NobVVVUW81L2tTek9XSitWWUg1L1cxeDEzRXB2bGlhCmp6ckZsN2lBYlhpZTJMUGNEc1d6YjRobkRXSGp2VWhiY256QkJDe" +
                    "i8xT0Z6UDFkcmI4SG1nQ29PRDRHMll4T00KR1J4Y0k5aGN5cyt1T1VGQ1dtTm9CdlZnRnVZVGVDaS92VVRIUWxWMW5zQXYxN" +
                    "25Mc2VubmdkZHNsYkF6UC9nMgo0a2c0b2RpRUQ2a09JbjZIeU1hZ2F5anpZZm54TVI4ZXRiam9nTkdSOXZVdVJNQWQ4MjBSV" +
                    "FA0THhIeVZmTWZRCmNqTTFraHh3c2Z3aWVwQ2NkV2xWOS93MWE2a2tVUW5CQnhoMXFJU21mcEk3K2t0MnFJaXNwRTcwZ1NGN" +
                    "TVBV0MKY2VTK3hRKzV6RzNoQnVXcG1UMDRpTjlLZWhkMFkvL1dIbzNFZlFJREFRQUJBb0lCQURpdDFiWmNXNjNXT3ZyWgpkT" +
                    "EhwTFE5blpjWDlqSHlPMzRDaG1HQUlsR2JtWHdadTd3aG1DSEhrMHNQdHdwdnhxRkZ0cHdzbU5RK3ROTGd4ClRQQ1pnakUxW" +
                    "nBOT0IyaHFIWmZSWXEzMVNXeUNnNmM4YVo5OFhQUTRTelBFb0dUS3VCaUNPWnFib01xdW1TWWMKK2pEeXViUzhBSTIzbDRpZ" +
                    "G9pM3lmZ3hNVFJCQlF5U05sY1l2bkw1NHVpcnBoK0ZiTzFQQXJuYmR0aElIemlvTQpOOHRQelhoQStXeTdONk1RMU9QUk8xd" +
                    "1QyUThiaEp0TVljeGJvcC9tcEtzYlBEWHB4M3l0clR4cWF4d2JISk1DClMvYVAxVXgyb1N0VUJ4Nm5lNFAvRFVVQkV2ME02R" +
                    "FRSSm5FK0N2bDA2YVdYUG5hY1EyU25LVXV2SkhGQ0NnelAKYWkvYllFRUNnWUVBNXN6OUR6ejI4MzNnSHYySlYraldPSnlza" +
                    "2gvdnltWXFuNUtyTEtQRkJSY1VFVEJIam53VApyWVNRb05mTHVCcU5kR3pwb2FhNE5IOHFoYzNzaTg2Y2ZmQlRlekVPVWYwQ" +
                    "U1QcmR5SC84RnRJd3RHNGFGSXlOCkF3Nk5BcFJJZDVKRUZHeW1lTlFVMWxVcFVzMkZLT1JrOWNrY2xsK0tFZVdmekFTUlBZe" +
                    "TBveVVDZ1lFQXkrZ2QKTk5Nd1Y4bjVDNmRzMVc2QUkyWTZ0dzZ2cUtVVGMvU0dVWUMyOENocElOSXNpdWFreVpGRkdZM0NsN" +
                    "3pVWm00SwpYREZtc2ZpeisxYk1FWm9kZEduT1RGN2tRLzRaN2JXMjBQWnorQnZ2WVRPbWF0amVvVVRjdFpkVXo1ellBakVKC" +
                    "npuaGhXZUxkVVNXcW5OaTAweDdTeXV2VVh0eXo3REhOb1VVdGlIa0NnWUJnOVlUcVBlWlE3SFNYRUZQK2htWlkKYWhsbFdkM" +
                    "VczZ3pSOUwvTWhSQmp6d296SG1FeFRwYkZzb2MveXVoZWMya3htLythVlh2Vk1nY2ZKeDlVckh1NQp2SmlWakVwRHoxR2hRZ" +
                    "0tpRklKRzVBNXAva2Nla3QwNmg0WmRxd1cybGMvYjlMa0swYTNmVE8rTFJhUEhSZ3ZUCjVhVUkxeUlkMnFXREEvZ3dMMGhEc" +
                    "1FLQmdRQ3BqZm03VTJGL25wTlkvWCtpZXFCU3owOURxUktvU1p4RGI3SEIKVkNiS3pNK2VXeVp1Mmh0dEFUOVVZR3pQZ0ZXZ" +
                    "VZ5S0dSdzMrTDdCNTcxTUIwQVZ1S0ExRHRDUmI1WS9wK3BCcQpjb1U4YXY1QzlaQU1pUW1YVUl1MjlIK3hvOXA2K0F3UGhFc" +
                    "HZWQlowdzcxN2J6ZnQxbE95S1NnUE9iYmpVUWFNCmM5bkpBUUtCZ0gvWGI1M0hKNytCSXh6N3VjRklRVDVFbENSWmU5QnRWQ" +
                    "TBWcmtOTVpGUTJIUXZxYlNQQVdFVVoKVmJZU3BvTXpKcCt4MUx5Vk0xZDYvaEY0d3p0NlFwa2RIeW5vU09KNGovNkFSK3Y0c" +
                    "WFJOFdGS0R0YU5SM2lwegpzQ1dpZGhYcU1CR2ttZFQvNzFiNTZaa2txbllnbS83Y1VCREVvK0NsRHcyTXdBTW5SQmRUCi0tL" +
                    "S0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==")
            .withCaCertData("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYR" +
                    "FRJeU1ETXlNakE0TURBMU5sb1hEVE15TURNeE9UQTRNREExTmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXVuCm5rNTBkUmdPZlhPMF" +
                    "RpdWpuamxlS2ZNRGxoaElBamJFZXU0ellZRXllM3VUallnL1JkbVZwYi9LdUx2YkdLbmsKRTZWcWtDMjhkSy9ZcnREZ2w5KzJ6ZTErOFBRK0FTSWVxZFhTM3pBTzRSOTdiOHpISUJsVnE5YVROZmxjYWlZSwpERWZ1WExTL2hTTEJ" +
                    "JczdRTkx6cDdTdFVld0lBSEZVZkNnMlBBQkhnN3dvOG9odFhKMllLR083Uk1TNzByUmtYCjlQVWFZaUZaM1RIeHlKUTkvdk5FVjBLbzErekRRMFBuUzlrQlVnUitQb0xrT1pKdGJnenM3eVI2MUN0QzFCeVkKdm03ckpJSEVkNjlP" +
                    "RHVORUJRTWFBMys1Y2RzNVpmc2lUUDRnbkFjVkRJT3pvd1hJWHIxSVZwUTRpRllERkVXaQpmTVRXV0wxZjBqckszVm41dDVzQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d" +
                    "0hRWURWUjBPQkJZRUZFZnBKd3J6NFZESlFZblM0bWhPQ1dWYy9OTHpNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRE1ncDRZQUdIa0RuckhpVzZzTwpuOUtIUmRBZktPOF" +
                    "FiYVhWbUVEVkJzQ1hCREZOMkYrSEhMN2lDbkhGdnM3V0J4UGVrSG5seE04c2FnOHpHVzVpCk9XVklxamRVOEFkZklxaEhsSEVyNjNpU2JkNUozcTVoTGNodk9MVFdDRUFZZ2pwTFg1V2dFa3BmQmJUQk5rSDUKM0UzdWQvdlBtQzd" +
                    "3OU5VOFVwejgwVUp1dE9zTHZOUkpMcHZ3NjRoZjlYVUxHY1N6Sm9JY1Q0TWkzYjJrcjl4Sgp3VFU3SHpVUEtmRVRhdkNOekdoay9FMDVIaTRtc3VWZkZwWkdnNmdkVHpvazdFQWVrNUlkVTdXR1RoSDZ5T1BoCm5PMUVtbGdNeUVM" +
                    "MElKbnBhZDR2L3RvOXNmQVNpdTNQQ0JWOU1uaDB3d3krM1ZRSThFSFZsQ2UvV1NUdkwwTVMKazJJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==")
            .withNamespace("default")
            .build();

    return properties;
  }
}
