---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - podsetgroup.javiroman.lan
  resources:
  - podsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podsetgroup.javiroman.lan
  resources:
  - podsets/finalizers
  verbs:
  - update
- apiGroups:
  - podsetgroup.javiroman.lan
  resources:
  - podsets/status
  verbs:
  - get
  - patch
  - update
