# -*- mode: ruby -*-
# vim: set ft=ruby ts=2 et :

VAGRANTFILE_API_VERSION = "2"

# Tested with Vagrant version:
Vagrant.require_version ">= 1.7.2"

# Require YAML module
require 'yaml'

def fail_with_message(msg)
    fail Vagrant::Errors::VagrantError.new, msg
end

def check_minimal_env()
    if ENV['ERLANG_CLUSTER'].nil? || ENV['ERLANG_CLUSTER'].empty?
        fail_with_message "You have to set ERLANG_CLUSTER environment variable!"
    end
end

# Sanity checks
check_minimal_env()

# Read YAML file with cluster details: The cluster flavor.
config_file = 'config/cluster-' + ENV['ERLANG_CLUSTER'] + ".yaml"
if File.exists?(config_file)
    cluster = YAML.load_file(config_file)
else
    fail_with_message "Cluster definition file: #{config_file} was not found!"
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Disabling the default /vagrant share
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = false
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  i = 0
  cluster.each do |servers|
    # VM definition
    config.vm.define servers["name"] do |node|
      node.vm.box = 'centos/7'
      node.vm.hostname = servers["name"]
      node.vm.network "private_network", ip: servers["ip"]
      node.vm.provider :libvirt do |domain|
        domain.uri = 'qemu+unix:///system'
        domain.driver = 'kvm'
        domain.memory = servers["mem"]
        domain.cpus = servers['cpu']
        if servers.key?('aditional_disk')
            domain.storage :file, :size => servers['aditional_disk']
        end
      end
      i += 1
      if i == cluster.length
          node.vm.provision :ansible do |ansible|
            ansible.verbose = "vv"
            ansible.inventory_path = "provisioning/inventory.py"
            ansible.playbook = "provisioning/site.yml"
            ansible.limit = "all"
          end # provison
      end # if
    end # config
  end # cluster
end # vagrant
